repos:
- repo: local
  hooks:
    - id: lint
      name: task lint
      entry: task lint
      language: system
      types: [python]
      pass_filenames: false
    - id: type-check
      name: task check
      entry: task check
      language: system
      types: [python]
      pass_filenames: false
    - id: format
      name: task format
      entry: task format
      language: system
      types: [python]
      pass_filenames: false