import { consume } from "@lit/context";
import { css, html, nothing } from "lit";
import type { TemplateResult } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import type { ProblemError, TokenBody, TokenInfo } from "@cofy/frontend-sdk";

import "@awesome.me/webawesome/dist/components/button/button.js";
import "@awesome.me/webawesome/dist/components/callout/callout.js";
import "@awesome.me/webawesome/dist/components/copy-button/copy-button.js";
import "@awesome.me/webawesome/dist/components/dialog/dialog.js";
import "@awesome.me/webawesome/dist/components/input/input.js";
import "../cofy-problem-details.js";

import { CofyElement } from "../../cofy-element.js";
import { communitySlugContext } from "../../context.js";
import { utilityStyles } from "../../theme/utility-styles.js";

/**
 * Creates an API token, or - given `token` - changes an existing one's description and expiry.
 *
 * A token's key is generated by the server and shown here once, right after creating it. Opened
 * and closed by its host through `open`: it reports `token-saved` with the token's name once
 * stored, and `dialog-closed` when dismissed - which, after creating, is once the key is copied.
 */
@customElement("cofy-token-dialog")
export class CofyTokenDialog extends CofyElement {
  public static override styles = [
    utilityStyles,
    css`
      :host {
        display: contents;
      }
    `,
  ];

  @consume({ context: communitySlugContext, subscribe: true })
  @state()
  public slug = "";

  @property({ type: Boolean }) public open = false;
  /** The token to change, or `null` to create one. */
  @property({ attribute: false }) public token: TokenInfo | null = null;

  @state() private name = "";
  @state() private description = "";
  /** The expiry date as the date input holds it, `YYYY-MM-DD`, or empty for none. */
  @state() private expires = "";
  /** The key of the token just created, shown until the dialog closes. */
  @state() private key: string | null = null;
  @state() private saving = false;
  @state() private error: ProblemError | null = null;

  public override willUpdate(changed: Map<string, unknown>): void {
    if (changed.has("open") && this.open) {
      this.name = this.token?.name ?? "";
      this.description = this.token?.description ?? "";
      this.expires = this.token?.expires?.slice(0, 10) ?? "";
      this.key = null;
      this.error = null;
    }
  }

  public override render(): TemplateResult {
    return html`
      <wa-dialog label=${this.label()} ?open=${this.open} @wa-hide=${(event: Event): void => this.onHide(event)}>
        ${this.key === null ? this.form() : this.created(this.key)}
      </wa-dialog>
    `;
  }

  private label(): string {
    if (this.key !== null) return this.t("tokenDialog.createdTitle", { name: this.name });
    if (this.token !== null) return this.t("tokenDialog.changeTitle", { name: this.token.name });
    return this.t("tokenDialog.title");
  }

  private form(): TemplateResult {
    const editing = this.token !== null;

    return html`
      <div class="wa-stack">
        ${this.error === null ? nothing : html`<cofy-problem-details .problem=${this.error}></cofy-problem-details>`}
        ${editing
          ? nothing
          : html`<wa-input
              label=${this.t("tokenDialog.name")}
              hint=${this.t("tokenDialog.nameHint")}
              required
              .value=${this.name}
              @input=${(event: Event): void => {
                this.name = this.inputValue(event);
              }}
            ></wa-input>`}
        <wa-input
          label=${this.t("tokenDialog.description")}
          hint=${this.t("tokenDialog.descriptionHint")}
          .value=${this.description}
          @input=${(event: Event): void => {
            this.description = this.inputValue(event);
          }}
        ></wa-input>
        <wa-input
          type="date"
          label=${this.t("tokenDialog.expires")}
          hint=${this.t("tokenDialog.expiresHint")}
          .value=${this.expires}
          @input=${(event: Event): void => {
            this.expires = this.inputValue(event);
          }}
        ></wa-input>
      </div>
      <wa-button slot="footer" appearance="plain" @click=${(): void => this.close()}>
        ${this.t("tokenDialog.cancel")}
      </wa-button>
      <wa-button
        slot="footer"
        variant="brand"
        ?disabled=${this.name === "" || this.saving}
        @click=${(): void => void this.save()}
      >
        ${this.saving ? this.t("tokenDialog.saving") : editing ? this.t("tokenDialog.save") : this.t("tokenDialog.create")}
      </wa-button>
    `;
  }

  /** The key of the token just created, to copy now: it is never shown again. */
  private created(key: string): TemplateResult {
    return html`
      <div class="wa-stack">
        <wa-callout variant="warning">${this.t("tokenDialog.copyWarning")}</wa-callout>
        <wa-input label=${this.t("tokenDialog.key")} readonly .value=${key}>
          <wa-copy-button
            slot="end"
            value=${key}
            copy-label=${this.t("tokenDialog.copy")}
            success-label=${this.t("tokenDialog.copied")}
            error-label=${this.t("tokenDialog.copyFailed")}
          ></wa-copy-button>
        </wa-input>
      </div>
      <wa-button slot="footer" variant="brand" @click=${(): void => this.close()}>${this.t("tokenDialog.done")}</wa-button>
    `;
  }

  private inputValue(event: Event): string {
    return (event.target as HTMLElement & { value?: string }).value ?? "";
  }

  private body(): TokenBody {
    return {
      name: this.name,
      description: this.description === "" ? null : this.description,
      // A token expires at the start of the day picked, in UTC.
      expires: this.expires === "" ? null : `${this.expires}T00:00:00Z`,
    };
  }

  private async save(): Promise<void> {
    const cofy = this.cofy;
    if (cofy === undefined) return;

    this.saving = true;
    this.error = null;
    try {
      if (this.token === null) {
        this.key = (await cofy.tokens.create(this.slug, this.body())).key;
      } else {
        const saved = await cofy.tokens.replace(this.slug, this.token.name, this.body());
        this.dispatchEvent(new CustomEvent("token-saved", { detail: { name: saved.name }, bubbles: true, composed: true }));
      }
    } catch (error) {
      this.error = error as ProblemError;
    } finally {
      this.saving = false;
    }
  }

  /** The dialog closing itself - Escape, its close button - rather than a nested element hiding. */
  private onHide(event: Event): void {
    if (event.target !== event.currentTarget) return;
    this.close();
  }

  private close(): void {
    this.dispatchEvent(new CustomEvent("dialog-closed", { bubbles: true, composed: true }));
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "cofy-token-dialog": CofyTokenDialog;
  }
}
